### ISSUE TITLE
fontawesome で画像を表示できません

### ISSUE THREAD

**Issue by na-ka-mu-ra-** [taikii/redmine_mermaid_macro#10]
初めまして。

こちらのプラグイン 1.0.5 をやや古いRedmine 3.4.6 で利用させていただいております。
プラグイン作成ありがとうございます！

こちらのプラグインは通常動作は特に不具合なく満足なのですが
どうにもfontawesome の画像を表示させることには失敗しておりまして少し困っております。

コードの例：

{{mermaid
mindmap
(test)
::icon(fa fa-bullseye)
}}

プラグインの設定URLが関係あるのかと、以下で試しましたが、特に変化はありませんでした。

https://cdn.jsdelivr.net/npm/mermaid@9/dist/mermaid.js
https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.js
https://cdn.jsdelivr.net/npm/mermaid@11.0.0-alpha.6/dist/mermaid.js
https://unpkg.com/mermaid/dist/mermaid.min.js

以上になります。

よろしくお願いいたします。

**Comment by na-ka-mu-ra-** [comment]
実際の症状はこちらです。
本来は左側に画像が出るはずなのですが出ておりません。
![fontawesome](https://github.com/taikii/redmine_mermaid_macro/assets/8348343/adfbc07c-6a7f-4ef9-8c4d-8594c37b4f5e)

**Comment by taikii** [comment]
@na-ka-mu-ra- 
https://github.com/alphanodes/additionals
を導入すると表示されるようになると思います。

**Comment by na-ka-mu-ra-** [comment]
@taikii 
ご返信ありがとうございます！
additionals プラグインをテスト環境で試してみた所、別の問題が生じたものの
無事fontawesome の画像が出るようになりました。

ありがとうございました。
