### ISSUE TITLE
Plugin not working in preview

### ISSUE THREAD

**Issue by hagig79** [taikii/redmine_mermaid_macro#5]
Mermaid diagram is not drawn in preview tab while editing.
However, saved page rendering works correctly.

- Redmine 4.2.8.stable
- Mermaid.js 9.2.2

**Comment by taikii** [comment]
@hagig79
It seems `mermaid.init()` didn't recognize the jQuery object, so I changed to the W3C selector.

また、以下のプラグインでもMermaidを使用できますので、こちらに乗り換えていただくのをおすすめします。
https://github.com/redmica/redmica_ui_extension

**Comment by hagig79** [comment]
Thank you for that, I was able to confirm that the preview worked!
