### ISSUE TITLE
Support easyredmine

### ISSUE THREAD

**Issue by GuidoLeibbrand** [taikii/redmine_mermaid_macro#8]
Hi,

is there a support for easyredmine?

I try out the plugin with easyredmine in version 12 (see https://www.easyredmine.com/).
Unfortunately, the diagrams are not generated. 

Source snipped from a try in a Redmine wiki page
```
<script src="/assets/diagram_versions-c9bc306a1d9987a87bebf3dd1e855122d16f6be5cf688475b48b81297642f5d6.js" defer="defer"></script> <link rel="stylesheet" media="all" href="/plugin_assets/redmine_mermaid_macro/stylesheets/redmine_mermaid_macro.css?1675414321" />
```

```
<div class="wiki wiki-page">
  <h2>Mermaid Macro Plugin Test</h2><pre><code class="language-plaintext">{{mermaid()
graph LR;
  A[start]
  B[end]
  A --&amp;gt; B
}}</code></pre>
</div>
```

```
<div id="diagram-modal" style="display: none">
</div> <script src="https://unpkg.com/mermaid@9.3.0/dist/mermaid.min.js"></script><script>
//<![CDATA[
mermaid.initialize({startOnLoad:true});var mermaidInitialized = 1;
//]]>
</script> 
```

Thanks,
Guido

**Comment by taikii** [comment]
@GuidoLeibbrand 
I don't have an environment where I can try easyredmine.
Marmeid.js can also be used with the RedMica UI extension. How about using it?
https://github.com/redmica/redmica_ui_extension

**Comment by GuidoLeibbrand** [comment]
Hi @taikii ,

I had contact with the company behind easyredmine. The recommended way is using the own implemented diagram editor (https://www.diagrams.net/). This editor also supports mermaid in text form and has its own (file) history.

These diagrams can then be linked in a ticket or wiki.
Example:
`{{include_diagram(2--test-diagram)}}`

I guess 3th plugins are not so welcome. 

I myself would like it much better to use the mermaid syntax directly in a wiki article instead of having a central file folder. But basically, I can work with the workaround
