### ISSUE TITLE
Mermaid 10 support (ESM)

### ISSUE THREAD

**Issue by jcatrysse** [taikii/redmine_mermaid_macro#9]
I noticed I could not use the mermaid 10 javascript from https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/mermaid.esm.min.mjs

Would it be possible to integrate this?

**Comment by taikii** [comment]
@jcatrysse Thanks for letting me know.
I just updated.
Use the `mermaid10` branch.

```
git clone -b mermaid10 https://github.com/taikii/redmine_mermaid_macro.git plugins/redmine_mermaid_macro
```

**Comment by jcatrysse** [comment]
Hi @taikii thank you very much for your blazing fast response!

However, I don't get the system to work correctly, mermaid diagrams are not rendering.

This is what I did:
1. I replaced the plugin with the new mermaid10 branch.
2. I restarted Redmine (and the complete Apache)
3. I changed the configuration to use: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs

When I opened the console, I noticed that the `mermaid.esm.min.mjs` file was never downloaded, as the `mermaid.min.js` was before.

I also get some errors:
![afbeelding](https://user-images.githubusercontent.com/23419642/227902782-c27dff5e-bbe6-424e-9948-6e067dc3b27a.png)

Am I doing something wrong?

**Comment by taikii** [comment]
@jcatrysse `javascript_tag` outputs a CDATA Section, but it was a syntax error in Firefox. So I changed it not to use `javascript_tag`. Could you please check again?
Also, if you have a problem, it would be helpful if you could let me know your environment.

```
<script>
//<![CDATA[
// some js code
//]]>
</script>
```

**Comment by jcatrysse** [comment]
Hi Taikii,

This is already one step ahead! Now the `[mermaid.esm.min.mjs]` file is downloading, but it seems the mimetype is blocked by the browser. I still need to look if and how that can me modified, but so you already have a heads-up.

I'm using Redmine5 on a FreeBSD 13.1 installation.

![image](https://user-images.githubusercontent.com/23419642/228157023-65b5bb03-1682-4436-875c-f8a39e285ff5.png)

**Comment by jcatrysse** [comment]
I was able to resolve this by adding the mime type to my httpd.conf.

`AddType text/javascript mjs` 

Thank you for resolving this issue!
